// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/ClientParametersProto.proto

package com.google.protos.speech.service;

public final class ClientParametersProto {
  private ClientParametersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ClientParametersOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional bool useWidebandSpeex = 1;
    boolean hasUseWidebandSpeex();
    boolean getUseWidebandSpeex();
    
    // optional bool enableHifiForWifi = 2;
    boolean hasEnableHifiForWifi();
    boolean getEnableHifiForWifi();
    
    // optional double bandwidthEstimatorMeanRttThresholdSecs = 3 [default = 0.15];
    boolean hasBandwidthEstimatorMeanRttThresholdSecs();
    double getBandwidthEstimatorMeanRttThresholdSecs();
    
    // optional double bandwidthEstimatorStdevRttThresholdSecs = 4 [default = 0.1];
    boolean hasBandwidthEstimatorStdevRttThresholdSecs();
    double getBandwidthEstimatorStdevRttThresholdSecs();
    
    // optional double bandwidthEstimatorPacketLossThreshold = 5 [default = 0.15];
    boolean hasBandwidthEstimatorPacketLossThreshold();
    double getBandwidthEstimatorPacketLossThreshold();
    
    // optional bool showHintOnHelp = 6;
    boolean hasShowHintOnHelp();
    boolean getShowHintOnHelp();
  }
  public static final class ClientParameters extends
      com.google.protobuf.GeneratedMessageLite
      implements ClientParametersOrBuilder {
    // Use ClientParameters.newBuilder() to construct.
    private ClientParameters(Builder builder) {
      super(builder);
    }
    private ClientParameters(boolean noInit) {}
    
    private static final ClientParameters defaultInstance;
    public static ClientParameters getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientParameters getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional bool useWidebandSpeex = 1;
    public static final int USEWIDEBANDSPEEX_FIELD_NUMBER = 1;
    private boolean useWidebandSpeex_;
    public boolean hasUseWidebandSpeex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getUseWidebandSpeex() {
      return useWidebandSpeex_;
    }
    
    // optional bool enableHifiForWifi = 2;
    public static final int ENABLEHIFIFORWIFI_FIELD_NUMBER = 2;
    private boolean enableHifiForWifi_;
    public boolean hasEnableHifiForWifi() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getEnableHifiForWifi() {
      return enableHifiForWifi_;
    }
    
    // optional double bandwidthEstimatorMeanRttThresholdSecs = 3 [default = 0.15];
    public static final int BANDWIDTHESTIMATORMEANRTTTHRESHOLDSECS_FIELD_NUMBER = 3;
    private double bandwidthEstimatorMeanRttThresholdSecs_;
    public boolean hasBandwidthEstimatorMeanRttThresholdSecs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getBandwidthEstimatorMeanRttThresholdSecs() {
      return bandwidthEstimatorMeanRttThresholdSecs_;
    }
    
    // optional double bandwidthEstimatorStdevRttThresholdSecs = 4 [default = 0.1];
    public static final int BANDWIDTHESTIMATORSTDEVRTTTHRESHOLDSECS_FIELD_NUMBER = 4;
    private double bandwidthEstimatorStdevRttThresholdSecs_;
    public boolean hasBandwidthEstimatorStdevRttThresholdSecs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getBandwidthEstimatorStdevRttThresholdSecs() {
      return bandwidthEstimatorStdevRttThresholdSecs_;
    }
    
    // optional double bandwidthEstimatorPacketLossThreshold = 5 [default = 0.15];
    public static final int BANDWIDTHESTIMATORPACKETLOSSTHRESHOLD_FIELD_NUMBER = 5;
    private double bandwidthEstimatorPacketLossThreshold_;
    public boolean hasBandwidthEstimatorPacketLossThreshold() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getBandwidthEstimatorPacketLossThreshold() {
      return bandwidthEstimatorPacketLossThreshold_;
    }
    
    // optional bool showHintOnHelp = 6;
    public static final int SHOWHINTONHELP_FIELD_NUMBER = 6;
    private boolean showHintOnHelp_;
    public boolean hasShowHintOnHelp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getShowHintOnHelp() {
      return showHintOnHelp_;
    }
    
    private void initFields() {
      useWidebandSpeex_ = false;
      enableHifiForWifi_ = false;
      bandwidthEstimatorMeanRttThresholdSecs_ = 0.15D;
      bandwidthEstimatorStdevRttThresholdSecs_ = 0.1D;
      bandwidthEstimatorPacketLossThreshold_ = 0.15D;
      showHintOnHelp_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, useWidebandSpeex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, enableHifiForWifi_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, bandwidthEstimatorMeanRttThresholdSecs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, bandwidthEstimatorStdevRttThresholdSecs_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, bandwidthEstimatorPacketLossThreshold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, showHintOnHelp_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, useWidebandSpeex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, enableHifiForWifi_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, bandwidthEstimatorMeanRttThresholdSecs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, bandwidthEstimatorStdevRttThresholdSecs_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, bandwidthEstimatorPacketLossThreshold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, showHintOnHelp_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientParameters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.service.ClientParametersProto.ClientParameters prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.service.ClientParametersProto.ClientParameters, Builder>
        implements com.google.protos.speech.service.ClientParametersProto.ClientParametersOrBuilder {
      // Construct using com.google.protos.speech.service.ClientParametersProto.ClientParameters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        useWidebandSpeex_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        enableHifiForWifi_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        bandwidthEstimatorMeanRttThresholdSecs_ = 0.15D;
        bitField0_ = (bitField0_ & ~0x00000004);
        bandwidthEstimatorStdevRttThresholdSecs_ = 0.1D;
        bitField0_ = (bitField0_ & ~0x00000008);
        bandwidthEstimatorPacketLossThreshold_ = 0.15D;
        bitField0_ = (bitField0_ & ~0x00000010);
        showHintOnHelp_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.service.ClientParametersProto.ClientParameters getDefaultInstanceForType() {
        return com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance();
      }
      
      public com.google.protos.speech.service.ClientParametersProto.ClientParameters build() {
        com.google.protos.speech.service.ClientParametersProto.ClientParameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.service.ClientParametersProto.ClientParameters buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.service.ClientParametersProto.ClientParameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.service.ClientParametersProto.ClientParameters buildPartial() {
        com.google.protos.speech.service.ClientParametersProto.ClientParameters result = new com.google.protos.speech.service.ClientParametersProto.ClientParameters(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.useWidebandSpeex_ = useWidebandSpeex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.enableHifiForWifi_ = enableHifiForWifi_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bandwidthEstimatorMeanRttThresholdSecs_ = bandwidthEstimatorMeanRttThresholdSecs_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bandwidthEstimatorStdevRttThresholdSecs_ = bandwidthEstimatorStdevRttThresholdSecs_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bandwidthEstimatorPacketLossThreshold_ = bandwidthEstimatorPacketLossThreshold_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.showHintOnHelp_ = showHintOnHelp_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.service.ClientParametersProto.ClientParameters other) {
        if (other == com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance()) return this;
        if (other.hasUseWidebandSpeex()) {
          setUseWidebandSpeex(other.getUseWidebandSpeex());
        }
        if (other.hasEnableHifiForWifi()) {
          setEnableHifiForWifi(other.getEnableHifiForWifi());
        }
        if (other.hasBandwidthEstimatorMeanRttThresholdSecs()) {
          setBandwidthEstimatorMeanRttThresholdSecs(other.getBandwidthEstimatorMeanRttThresholdSecs());
        }
        if (other.hasBandwidthEstimatorStdevRttThresholdSecs()) {
          setBandwidthEstimatorStdevRttThresholdSecs(other.getBandwidthEstimatorStdevRttThresholdSecs());
        }
        if (other.hasBandwidthEstimatorPacketLossThreshold()) {
          setBandwidthEstimatorPacketLossThreshold(other.getBandwidthEstimatorPacketLossThreshold());
        }
        if (other.hasShowHintOnHelp()) {
          setShowHintOnHelp(other.getShowHintOnHelp());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              useWidebandSpeex_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              enableHifiForWifi_ = input.readBool();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              bandwidthEstimatorMeanRttThresholdSecs_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              bandwidthEstimatorStdevRttThresholdSecs_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              bandwidthEstimatorPacketLossThreshold_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              showHintOnHelp_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool useWidebandSpeex = 1;
      private boolean useWidebandSpeex_ ;
      public boolean hasUseWidebandSpeex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getUseWidebandSpeex() {
        return useWidebandSpeex_;
      }
      public Builder setUseWidebandSpeex(boolean value) {
        bitField0_ |= 0x00000001;
        useWidebandSpeex_ = value;
        
        return this;
      }
      public Builder clearUseWidebandSpeex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        useWidebandSpeex_ = false;
        
        return this;
      }
      
      // optional bool enableHifiForWifi = 2;
      private boolean enableHifiForWifi_ ;
      public boolean hasEnableHifiForWifi() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getEnableHifiForWifi() {
        return enableHifiForWifi_;
      }
      public Builder setEnableHifiForWifi(boolean value) {
        bitField0_ |= 0x00000002;
        enableHifiForWifi_ = value;
        
        return this;
      }
      public Builder clearEnableHifiForWifi() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enableHifiForWifi_ = false;
        
        return this;
      }
      
      // optional double bandwidthEstimatorMeanRttThresholdSecs = 3 [default = 0.15];
      private double bandwidthEstimatorMeanRttThresholdSecs_ = 0.15D;
      public boolean hasBandwidthEstimatorMeanRttThresholdSecs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getBandwidthEstimatorMeanRttThresholdSecs() {
        return bandwidthEstimatorMeanRttThresholdSecs_;
      }
      public Builder setBandwidthEstimatorMeanRttThresholdSecs(double value) {
        bitField0_ |= 0x00000004;
        bandwidthEstimatorMeanRttThresholdSecs_ = value;
        
        return this;
      }
      public Builder clearBandwidthEstimatorMeanRttThresholdSecs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bandwidthEstimatorMeanRttThresholdSecs_ = 0.15D;
        
        return this;
      }
      
      // optional double bandwidthEstimatorStdevRttThresholdSecs = 4 [default = 0.1];
      private double bandwidthEstimatorStdevRttThresholdSecs_ = 0.1D;
      public boolean hasBandwidthEstimatorStdevRttThresholdSecs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getBandwidthEstimatorStdevRttThresholdSecs() {
        return bandwidthEstimatorStdevRttThresholdSecs_;
      }
      public Builder setBandwidthEstimatorStdevRttThresholdSecs(double value) {
        bitField0_ |= 0x00000008;
        bandwidthEstimatorStdevRttThresholdSecs_ = value;
        
        return this;
      }
      public Builder clearBandwidthEstimatorStdevRttThresholdSecs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bandwidthEstimatorStdevRttThresholdSecs_ = 0.1D;
        
        return this;
      }
      
      // optional double bandwidthEstimatorPacketLossThreshold = 5 [default = 0.15];
      private double bandwidthEstimatorPacketLossThreshold_ = 0.15D;
      public boolean hasBandwidthEstimatorPacketLossThreshold() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getBandwidthEstimatorPacketLossThreshold() {
        return bandwidthEstimatorPacketLossThreshold_;
      }
      public Builder setBandwidthEstimatorPacketLossThreshold(double value) {
        bitField0_ |= 0x00000010;
        bandwidthEstimatorPacketLossThreshold_ = value;
        
        return this;
      }
      public Builder clearBandwidthEstimatorPacketLossThreshold() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bandwidthEstimatorPacketLossThreshold_ = 0.15D;
        
        return this;
      }
      
      // optional bool showHintOnHelp = 6;
      private boolean showHintOnHelp_ ;
      public boolean hasShowHintOnHelp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getShowHintOnHelp() {
        return showHintOnHelp_;
      }
      public Builder setShowHintOnHelp(boolean value) {
        bitField0_ |= 0x00000020;
        showHintOnHelp_ = value;
        
        return this;
      }
      public Builder clearShowHintOnHelp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        showHintOnHelp_ = false;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ClientParameters)
    }
    
    static {
      defaultInstance = new ClientParameters(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ClientParameters)
  }
  
  public interface ClientExperimentConfigOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional .ClientParameters clientParameters = 1;
    boolean hasClientParameters();
    com.google.protos.speech.service.ClientParametersProto.ClientParameters getClientParameters();
  }
  public static final class ClientExperimentConfig extends
      com.google.protobuf.GeneratedMessageLite
      implements ClientExperimentConfigOrBuilder {
    // Use ClientExperimentConfig.newBuilder() to construct.
    private ClientExperimentConfig(Builder builder) {
      super(builder);
    }
    private ClientExperimentConfig(boolean noInit) {}
    
    private static final ClientExperimentConfig defaultInstance;
    public static ClientExperimentConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientExperimentConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional .ClientParameters clientParameters = 1;
    public static final int CLIENTPARAMETERS_FIELD_NUMBER = 1;
    private com.google.protos.speech.service.ClientParametersProto.ClientParameters clientParameters_;
    public boolean hasClientParameters() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protos.speech.service.ClientParametersProto.ClientParameters getClientParameters() {
      return clientParameters_;
    }
    
    private void initFields() {
      clientParameters_ = com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, clientParameters_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, clientParameters_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig, Builder>
        implements com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfigOrBuilder {
      // Construct using com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        clientParameters_ = com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig getDefaultInstanceForType() {
        return com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig.getDefaultInstance();
      }
      
      public com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig build() {
        com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig buildPartial() {
        com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig result = new com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientParameters_ = clientParameters_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig other) {
        if (other == com.google.protos.speech.service.ClientParametersProto.ClientExperimentConfig.getDefaultInstance()) return this;
        if (other.hasClientParameters()) {
          mergeClientParameters(other.getClientParameters());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.speech.service.ClientParametersProto.ClientParameters.Builder subBuilder = com.google.protos.speech.service.ClientParametersProto.ClientParameters.newBuilder();
              if (hasClientParameters()) {
                subBuilder.mergeFrom(getClientParameters());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClientParameters(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .ClientParameters clientParameters = 1;
      private com.google.protos.speech.service.ClientParametersProto.ClientParameters clientParameters_ = com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance();
      public boolean hasClientParameters() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protos.speech.service.ClientParametersProto.ClientParameters getClientParameters() {
        return clientParameters_;
      }
      public Builder setClientParameters(com.google.protos.speech.service.ClientParametersProto.ClientParameters value) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientParameters_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setClientParameters(
          com.google.protos.speech.service.ClientParametersProto.ClientParameters.Builder builderForValue) {
        clientParameters_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeClientParameters(com.google.protos.speech.service.ClientParametersProto.ClientParameters value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            clientParameters_ != com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance()) {
          clientParameters_ =
            com.google.protos.speech.service.ClientParametersProto.ClientParameters.newBuilder(clientParameters_).mergeFrom(value).buildPartial();
        } else {
          clientParameters_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearClientParameters() {
        clientParameters_ = com.google.protos.speech.service.ClientParametersProto.ClientParameters.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ClientExperimentConfig)
    }
    
    static {
      defaultInstance = new ClientExperimentConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ClientExperimentConfig)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
