// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/RecognitionResultSet.proto

package com.google.protos.multimodal;

public final class RecognitionResultSet {
  private RecognitionResultSet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RecognitionResultProtoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string result = 1;
    boolean hasResult();
    String getResult();
    
    // required int32 confidence = 2;
    boolean hasConfidence();
    int getConfidence();
    
    // optional int32 nlconfidence = 3;
    boolean hasNlconfidence();
    int getNlconfidence();
    
    // optional string grammarContext = 4;
    boolean hasGrammarContext();
    String getGrammarContext();
  }
  public static final class RecognitionResultProto extends
      com.google.protobuf.GeneratedMessageLite
      implements RecognitionResultProtoOrBuilder {
    // Use RecognitionResultProto.newBuilder() to construct.
    private RecognitionResultProto(Builder builder) {
      super(builder);
    }
    private RecognitionResultProto(boolean noInit) {}
    
    private static final RecognitionResultProto defaultInstance;
    public static RecognitionResultProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecognitionResultProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.lang.Object result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          result_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 confidence = 2;
    public static final int CONFIDENCE_FIELD_NUMBER = 2;
    private int confidence_;
    public boolean hasConfidence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getConfidence() {
      return confidence_;
    }
    
    // optional int32 nlconfidence = 3;
    public static final int NLCONFIDENCE_FIELD_NUMBER = 3;
    private int nlconfidence_;
    public boolean hasNlconfidence() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNlconfidence() {
      return nlconfidence_;
    }
    
    // optional string grammarContext = 4;
    public static final int GRAMMARCONTEXT_FIELD_NUMBER = 4;
    private java.lang.Object grammarContext_;
    public boolean hasGrammarContext() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getGrammarContext() {
      java.lang.Object ref = grammarContext_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          grammarContext_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGrammarContextBytes() {
      java.lang.Object ref = grammarContext_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        grammarContext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      result_ = "";
      confidence_ = 0;
      nlconfidence_ = 0;
      grammarContext_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConfidence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, confidence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, nlconfidence_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGrammarContextBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, confidence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nlconfidence_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGrammarContextBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto, Builder>
        implements com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProtoOrBuilder {
      // Construct using com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        confidence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        nlconfidence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        grammarContext_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto getDefaultInstanceForType() {
        return com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.getDefaultInstance();
      }
      
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto build() {
        com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto buildPartial() {
        com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto result = new com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.confidence_ = confidence_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nlconfidence_ = nlconfidence_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.grammarContext_ = grammarContext_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto other) {
        if (other == com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasConfidence()) {
          setConfidence(other.getConfidence());
        }
        if (other.hasNlconfidence()) {
          setNlconfidence(other.getNlconfidence());
        }
        if (other.hasGrammarContext()) {
          setGrammarContext(other.getGrammarContext());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!hasConfidence()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              result_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              confidence_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              nlconfidence_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              grammarContext_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string result = 1;
      private java.lang.Object result_ = "";
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResult(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        
        return this;
      }
      void setResult(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        
      }
      
      // required int32 confidence = 2;
      private int confidence_ ;
      public boolean hasConfidence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getConfidence() {
        return confidence_;
      }
      public Builder setConfidence(int value) {
        bitField0_ |= 0x00000002;
        confidence_ = value;
        
        return this;
      }
      public Builder clearConfidence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confidence_ = 0;
        
        return this;
      }
      
      // optional int32 nlconfidence = 3;
      private int nlconfidence_ ;
      public boolean hasNlconfidence() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNlconfidence() {
        return nlconfidence_;
      }
      public Builder setNlconfidence(int value) {
        bitField0_ |= 0x00000004;
        nlconfidence_ = value;
        
        return this;
      }
      public Builder clearNlconfidence() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nlconfidence_ = 0;
        
        return this;
      }
      
      // optional string grammarContext = 4;
      private java.lang.Object grammarContext_ = "";
      public boolean hasGrammarContext() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getGrammarContext() {
        java.lang.Object ref = grammarContext_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          grammarContext_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGrammarContext(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        grammarContext_ = value;
        
        return this;
      }
      public Builder clearGrammarContext() {
        bitField0_ = (bitField0_ & ~0x00000008);
        grammarContext_ = getDefaultInstance().getGrammarContext();
        
        return this;
      }
      void setGrammarContext(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        grammarContext_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:RecognitionResultProto)
    }
    
    static {
      defaultInstance = new RecognitionResultProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RecognitionResultProto)
  }
  
  public interface RecognitionResultSetProtoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .RecognitionResultProto results = 1;
    java.util.List<com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto> 
        getResultsList();
    com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto getResults(int index);
    int getResultsCount();
    
    // optional int32 confidencehighthreshold = 2;
    boolean hasConfidencehighthreshold();
    int getConfidencehighthreshold();
    
    // optional int32 confidencelowthreshold = 3;
    boolean hasConfidencelowthreshold();
    int getConfidencelowthreshold();
  }
  public static final class RecognitionResultSetProto extends
      com.google.protobuf.GeneratedMessageLite
      implements RecognitionResultSetProtoOrBuilder {
    // Use RecognitionResultSetProto.newBuilder() to construct.
    private RecognitionResultSetProto(Builder builder) {
      super(builder);
    }
    private RecognitionResultSetProto(boolean noInit) {}
    
    private static final RecognitionResultSetProto defaultInstance;
    public static RecognitionResultSetProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecognitionResultSetProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // repeated .RecognitionResultProto results = 1;
    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto> results_;
    public java.util.List<com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto> getResultsList() {
      return results_;
    }
    public java.util.List<? extends com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProtoOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    public int getResultsCount() {
      return results_.size();
    }
    public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto getResults(int index) {
      return results_.get(index);
    }
    public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProtoOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }
    
    // optional int32 confidencehighthreshold = 2;
    public static final int CONFIDENCEHIGHTHRESHOLD_FIELD_NUMBER = 2;
    private int confidencehighthreshold_;
    public boolean hasConfidencehighthreshold() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getConfidencehighthreshold() {
      return confidencehighthreshold_;
    }
    
    // optional int32 confidencelowthreshold = 3;
    public static final int CONFIDENCELOWTHRESHOLD_FIELD_NUMBER = 3;
    private int confidencelowthreshold_;
    public boolean hasConfidencelowthreshold() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getConfidencelowthreshold() {
      return confidencelowthreshold_;
    }
    
    private void initFields() {
      results_ = java.util.Collections.emptyList();
      confidencehighthreshold_ = 0;
      confidencelowthreshold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getResultsCount(); i++) {
        if (!getResults(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(1, results_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, confidencehighthreshold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, confidencelowthreshold_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, confidencehighthreshold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, confidencelowthreshold_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto, Builder>
        implements com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProtoOrBuilder {
      // Construct using com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        confidencehighthreshold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        confidencelowthreshold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto getDefaultInstanceForType() {
        return com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto.getDefaultInstance();
      }
      
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto build() {
        com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto buildPartial() {
        com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto result = new com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.confidencehighthreshold_ = confidencehighthreshold_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.confidencelowthreshold_ = confidencelowthreshold_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto other) {
        if (other == com.google.protos.multimodal.RecognitionResultSet.RecognitionResultSetProto.getDefaultInstance()) return this;
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          
        }
        if (other.hasConfidencehighthreshold()) {
          setConfidencehighthreshold(other.getConfidencehighthreshold());
        }
        if (other.hasConfidencelowthreshold()) {
          setConfidencelowthreshold(other.getConfidencelowthreshold());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getResultsCount(); i++) {
          if (!getResults(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.Builder subBuilder = com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResults(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              confidencehighthreshold_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              confidencelowthreshold_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .RecognitionResultProto results = 1;
      private java.util.List<com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = new java.util.ArrayList<com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto>(results_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto> getResultsList() {
        return java.util.Collections.unmodifiableList(results_);
      }
      public int getResultsCount() {
        return results_.size();
      }
      public com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto getResults(int index) {
        return results_.get(index);
      }
      public Builder setResults(
          int index, com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        
        return this;
      }
      public Builder setResults(
          int index, com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.Builder builderForValue) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addResults(com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        
        return this;
      }
      public Builder addResults(
          int index, com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        
        return this;
      }
      public Builder addResults(
          com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.Builder builderForValue) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        
        return this;
      }
      public Builder addResults(
          int index, com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto.Builder builderForValue) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllResults(
          java.lang.Iterable<? extends com.google.protos.multimodal.RecognitionResultSet.RecognitionResultProto> values) {
        ensureResultsIsMutable();
        super.addAll(values, results_);
        
        return this;
      }
      public Builder clearResults() {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeResults(int index) {
        ensureResultsIsMutable();
        results_.remove(index);
        
        return this;
      }
      
      // optional int32 confidencehighthreshold = 2;
      private int confidencehighthreshold_ ;
      public boolean hasConfidencehighthreshold() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getConfidencehighthreshold() {
        return confidencehighthreshold_;
      }
      public Builder setConfidencehighthreshold(int value) {
        bitField0_ |= 0x00000002;
        confidencehighthreshold_ = value;
        
        return this;
      }
      public Builder clearConfidencehighthreshold() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confidencehighthreshold_ = 0;
        
        return this;
      }
      
      // optional int32 confidencelowthreshold = 3;
      private int confidencelowthreshold_ ;
      public boolean hasConfidencelowthreshold() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getConfidencelowthreshold() {
        return confidencelowthreshold_;
      }
      public Builder setConfidencelowthreshold(int value) {
        bitField0_ |= 0x00000004;
        confidencelowthreshold_ = value;
        
        return this;
      }
      public Builder clearConfidencelowthreshold() {
        bitField0_ = (bitField0_ & ~0x00000004);
        confidencelowthreshold_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RecognitionResultSetProto)
    }
    
    static {
      defaultInstance = new RecognitionResultSetProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RecognitionResultSetProto)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
