// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/Alternates.proto

package com.google.protos.speech.common;

public final class Alternates {
  private Alternates() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AlternateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string text = 1;
    boolean hasText();
    String getText();
    
    // optional float confidence = 2;
    boolean hasConfidence();
    float getConfidence();
  }
  public static final class Alternate extends
      com.google.protobuf.GeneratedMessageLite
      implements AlternateOrBuilder {
    // Use Alternate.newBuilder() to construct.
    private Alternate(Builder builder) {
      super(builder);
    }
    private Alternate(boolean noInit) {}
    
    private static final Alternate defaultInstance;
    public static Alternate getDefaultInstance() {
      return defaultInstance;
    }
    
    public Alternate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional float confidence = 2;
    public static final int CONFIDENCE_FIELD_NUMBER = 2;
    private float confidence_;
    public boolean hasConfidence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getConfidence() {
      return confidence_;
    }
    
    private void initFields() {
      text_ = "";
      confidence_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, confidence_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, confidence_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.Alternate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.common.Alternates.Alternate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.common.Alternates.Alternate, Builder>
        implements com.google.protos.speech.common.Alternates.AlternateOrBuilder {
      // Construct using com.google.protos.speech.common.Alternates.Alternate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        confidence_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.common.Alternates.Alternate getDefaultInstanceForType() {
        return com.google.protos.speech.common.Alternates.Alternate.getDefaultInstance();
      }
      
      public com.google.protos.speech.common.Alternates.Alternate build() {
        com.google.protos.speech.common.Alternates.Alternate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.common.Alternates.Alternate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.common.Alternates.Alternate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.common.Alternates.Alternate buildPartial() {
        com.google.protos.speech.common.Alternates.Alternate result = new com.google.protos.speech.common.Alternates.Alternate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.confidence_ = confidence_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.common.Alternates.Alternate other) {
        if (other == com.google.protos.speech.common.Alternates.Alternate.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasConfidence()) {
          setConfidence(other.getConfidence());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              confidence_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string text = 1;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        text_ = value;
        
      }
      
      // optional float confidence = 2;
      private float confidence_ ;
      public boolean hasConfidence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getConfidence() {
        return confidence_;
      }
      public Builder setConfidence(float value) {
        bitField0_ |= 0x00000002;
        confidence_ = value;
        
        return this;
      }
      public Builder clearConfidence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confidence_ = 0F;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Alternate)
    }
    
    static {
      defaultInstance = new Alternate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Alternate)
  }
  
  public interface AlternateParamsOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 maxSpanLength = 1;
    boolean hasMaxSpanLength();
    int getMaxSpanLength();
    
    // optional int32 maxTotalSpanLength = 2;
    boolean hasMaxTotalSpanLength();
    int getMaxTotalSpanLength();
  }
  public static final class AlternateParams extends
      com.google.protobuf.GeneratedMessageLite
      implements AlternateParamsOrBuilder {
    // Use AlternateParams.newBuilder() to construct.
    private AlternateParams(Builder builder) {
      super(builder);
    }
    private AlternateParams(boolean noInit) {}
    
    private static final AlternateParams defaultInstance;
    public static AlternateParams getDefaultInstance() {
      return defaultInstance;
    }
    
    public AlternateParams getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 maxSpanLength = 1;
    public static final int MAXSPANLENGTH_FIELD_NUMBER = 1;
    private int maxSpanLength_;
    public boolean hasMaxSpanLength() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMaxSpanLength() {
      return maxSpanLength_;
    }
    
    // optional int32 maxTotalSpanLength = 2;
    public static final int MAXTOTALSPANLENGTH_FIELD_NUMBER = 2;
    private int maxTotalSpanLength_;
    public boolean hasMaxTotalSpanLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMaxTotalSpanLength() {
      return maxTotalSpanLength_;
    }
    
    private void initFields() {
      maxSpanLength_ = 0;
      maxTotalSpanLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, maxSpanLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxTotalSpanLength_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxSpanLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxTotalSpanLength_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.common.Alternates.AlternateParams prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.common.Alternates.AlternateParams, Builder>
        implements com.google.protos.speech.common.Alternates.AlternateParamsOrBuilder {
      // Construct using com.google.protos.speech.common.Alternates.AlternateParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        maxSpanLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxTotalSpanLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.common.Alternates.AlternateParams getDefaultInstanceForType() {
        return com.google.protos.speech.common.Alternates.AlternateParams.getDefaultInstance();
      }
      
      public com.google.protos.speech.common.Alternates.AlternateParams build() {
        com.google.protos.speech.common.Alternates.AlternateParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.common.Alternates.AlternateParams buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.common.Alternates.AlternateParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.common.Alternates.AlternateParams buildPartial() {
        com.google.protos.speech.common.Alternates.AlternateParams result = new com.google.protos.speech.common.Alternates.AlternateParams(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxSpanLength_ = maxSpanLength_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxTotalSpanLength_ = maxTotalSpanLength_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.common.Alternates.AlternateParams other) {
        if (other == com.google.protos.speech.common.Alternates.AlternateParams.getDefaultInstance()) return this;
        if (other.hasMaxSpanLength()) {
          setMaxSpanLength(other.getMaxSpanLength());
        }
        if (other.hasMaxTotalSpanLength()) {
          setMaxTotalSpanLength(other.getMaxTotalSpanLength());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              maxSpanLength_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxTotalSpanLength_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 maxSpanLength = 1;
      private int maxSpanLength_ ;
      public boolean hasMaxSpanLength() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMaxSpanLength() {
        return maxSpanLength_;
      }
      public Builder setMaxSpanLength(int value) {
        bitField0_ |= 0x00000001;
        maxSpanLength_ = value;
        
        return this;
      }
      public Builder clearMaxSpanLength() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSpanLength_ = 0;
        
        return this;
      }
      
      // optional int32 maxTotalSpanLength = 2;
      private int maxTotalSpanLength_ ;
      public boolean hasMaxTotalSpanLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMaxTotalSpanLength() {
        return maxTotalSpanLength_;
      }
      public Builder setMaxTotalSpanLength(int value) {
        bitField0_ |= 0x00000002;
        maxTotalSpanLength_ = value;
        
        return this;
      }
      public Builder clearMaxTotalSpanLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxTotalSpanLength_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:AlternateParams)
    }
    
    static {
      defaultInstance = new AlternateParams(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:AlternateParams)
  }
  
  public interface AlternateSpanOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int32 start = 1;
    boolean hasStart();
    int getStart();
    
    // required int32 length = 2;
    boolean hasLength();
    int getLength();
    
    // repeated .Alternate alternates = 3;
    java.util.List<com.google.protos.speech.common.Alternates.Alternate> 
        getAlternatesList();
    com.google.protos.speech.common.Alternates.Alternate getAlternates(int index);
    int getAlternatesCount();
    
    // optional float confidence = 4;
    boolean hasConfidence();
    float getConfidence();
  }
  public static final class AlternateSpan extends
      com.google.protobuf.GeneratedMessageLite
      implements AlternateSpanOrBuilder {
    // Use AlternateSpan.newBuilder() to construct.
    private AlternateSpan(Builder builder) {
      super(builder);
    }
    private AlternateSpan(boolean noInit) {}
    
    private static final AlternateSpan defaultInstance;
    public static AlternateSpan getDefaultInstance() {
      return defaultInstance;
    }
    
    public AlternateSpan getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int32 start = 1;
    public static final int START_FIELD_NUMBER = 1;
    private int start_;
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getStart() {
      return start_;
    }
    
    // required int32 length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLength() {
      return length_;
    }
    
    // repeated .Alternate alternates = 3;
    public static final int ALTERNATES_FIELD_NUMBER = 3;
    private java.util.List<com.google.protos.speech.common.Alternates.Alternate> alternates_;
    public java.util.List<com.google.protos.speech.common.Alternates.Alternate> getAlternatesList() {
      return alternates_;
    }
    public java.util.List<? extends com.google.protos.speech.common.Alternates.AlternateOrBuilder> 
        getAlternatesOrBuilderList() {
      return alternates_;
    }
    public int getAlternatesCount() {
      return alternates_.size();
    }
    public com.google.protos.speech.common.Alternates.Alternate getAlternates(int index) {
      return alternates_.get(index);
    }
    public com.google.protos.speech.common.Alternates.AlternateOrBuilder getAlternatesOrBuilder(
        int index) {
      return alternates_.get(index);
    }
    
    // optional float confidence = 4;
    public static final int CONFIDENCE_FIELD_NUMBER = 4;
    private float confidence_;
    public boolean hasConfidence() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getConfidence() {
      return confidence_;
    }
    
    private void initFields() {
      start_ = 0;
      length_ = 0;
      alternates_ = java.util.Collections.emptyList();
      confidence_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAlternatesCount(); i++) {
        if (!getAlternates(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, start_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, length_);
      }
      for (int i = 0; i < alternates_.size(); i++) {
        output.writeMessage(3, alternates_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(4, confidence_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, start_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      for (int i = 0; i < alternates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, alternates_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, confidence_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.AlternateSpan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.common.Alternates.AlternateSpan prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.common.Alternates.AlternateSpan, Builder>
        implements com.google.protos.speech.common.Alternates.AlternateSpanOrBuilder {
      // Construct using com.google.protos.speech.common.Alternates.AlternateSpan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        start_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        alternates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        confidence_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.common.Alternates.AlternateSpan getDefaultInstanceForType() {
        return com.google.protos.speech.common.Alternates.AlternateSpan.getDefaultInstance();
      }
      
      public com.google.protos.speech.common.Alternates.AlternateSpan build() {
        com.google.protos.speech.common.Alternates.AlternateSpan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.common.Alternates.AlternateSpan buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.common.Alternates.AlternateSpan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.common.Alternates.AlternateSpan buildPartial() {
        com.google.protos.speech.common.Alternates.AlternateSpan result = new com.google.protos.speech.common.Alternates.AlternateSpan(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          alternates_ = java.util.Collections.unmodifiableList(alternates_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.alternates_ = alternates_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.confidence_ = confidence_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.common.Alternates.AlternateSpan other) {
        if (other == com.google.protos.speech.common.Alternates.AlternateSpan.getDefaultInstance()) return this;
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (!other.alternates_.isEmpty()) {
          if (alternates_.isEmpty()) {
            alternates_ = other.alternates_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAlternatesIsMutable();
            alternates_.addAll(other.alternates_);
          }
          
        }
        if (other.hasConfidence()) {
          setConfidence(other.getConfidence());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStart()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        for (int i = 0; i < getAlternatesCount(); i++) {
          if (!getAlternates(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              start_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protos.speech.common.Alternates.Alternate.Builder subBuilder = com.google.protos.speech.common.Alternates.Alternate.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAlternates(subBuilder.buildPartial());
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              confidence_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 start = 1;
      private int start_ ;
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStart() {
        return start_;
      }
      public Builder setStart(int value) {
        bitField0_ |= 0x00000001;
        start_ = value;
        
        return this;
      }
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = 0;
        
        return this;
      }
      
      // required int32 length = 2;
      private int length_ ;
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLength() {
        return length_;
      }
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        
        return this;
      }
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        
        return this;
      }
      
      // repeated .Alternate alternates = 3;
      private java.util.List<com.google.protos.speech.common.Alternates.Alternate> alternates_ =
        java.util.Collections.emptyList();
      private void ensureAlternatesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          alternates_ = new java.util.ArrayList<com.google.protos.speech.common.Alternates.Alternate>(alternates_);
          bitField0_ |= 0x00000004;
         }
      }
      
      public java.util.List<com.google.protos.speech.common.Alternates.Alternate> getAlternatesList() {
        return java.util.Collections.unmodifiableList(alternates_);
      }
      public int getAlternatesCount() {
        return alternates_.size();
      }
      public com.google.protos.speech.common.Alternates.Alternate getAlternates(int index) {
        return alternates_.get(index);
      }
      public Builder setAlternates(
          int index, com.google.protos.speech.common.Alternates.Alternate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternatesIsMutable();
        alternates_.set(index, value);
        
        return this;
      }
      public Builder setAlternates(
          int index, com.google.protos.speech.common.Alternates.Alternate.Builder builderForValue) {
        ensureAlternatesIsMutable();
        alternates_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addAlternates(com.google.protos.speech.common.Alternates.Alternate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternatesIsMutable();
        alternates_.add(value);
        
        return this;
      }
      public Builder addAlternates(
          int index, com.google.protos.speech.common.Alternates.Alternate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternatesIsMutable();
        alternates_.add(index, value);
        
        return this;
      }
      public Builder addAlternates(
          com.google.protos.speech.common.Alternates.Alternate.Builder builderForValue) {
        ensureAlternatesIsMutable();
        alternates_.add(builderForValue.build());
        
        return this;
      }
      public Builder addAlternates(
          int index, com.google.protos.speech.common.Alternates.Alternate.Builder builderForValue) {
        ensureAlternatesIsMutable();
        alternates_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllAlternates(
          java.lang.Iterable<? extends com.google.protos.speech.common.Alternates.Alternate> values) {
        ensureAlternatesIsMutable();
        super.addAll(values, alternates_);
        
        return this;
      }
      public Builder clearAlternates() {
        alternates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      public Builder removeAlternates(int index) {
        ensureAlternatesIsMutable();
        alternates_.remove(index);
        
        return this;
      }
      
      // optional float confidence = 4;
      private float confidence_ ;
      public boolean hasConfidence() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getConfidence() {
        return confidence_;
      }
      public Builder setConfidence(float value) {
        bitField0_ |= 0x00000008;
        confidence_ = value;
        
        return this;
      }
      public Builder clearConfidence() {
        bitField0_ = (bitField0_ & ~0x00000008);
        confidence_ = 0F;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:AlternateSpan)
    }
    
    static {
      defaultInstance = new AlternateSpan(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:AlternateSpan)
  }
  
  public interface RecognitionClientAlternatesOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .AlternateSpan span = 1;
    java.util.List<com.google.protos.speech.common.Alternates.AlternateSpan> 
        getSpanList();
    com.google.protos.speech.common.Alternates.AlternateSpan getSpan(int index);
    int getSpanCount();
    
    // required int32 maxSpanLength = 2;
    boolean hasMaxSpanLength();
    int getMaxSpanLength();
  }
  public static final class RecognitionClientAlternates extends
      com.google.protobuf.GeneratedMessageLite
      implements RecognitionClientAlternatesOrBuilder {
    // Use RecognitionClientAlternates.newBuilder() to construct.
    private RecognitionClientAlternates(Builder builder) {
      super(builder);
    }
    private RecognitionClientAlternates(boolean noInit) {}
    
    private static final RecognitionClientAlternates defaultInstance;
    public static RecognitionClientAlternates getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecognitionClientAlternates getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // repeated .AlternateSpan span = 1;
    public static final int SPAN_FIELD_NUMBER = 1;
    private java.util.List<com.google.protos.speech.common.Alternates.AlternateSpan> span_;
    public java.util.List<com.google.protos.speech.common.Alternates.AlternateSpan> getSpanList() {
      return span_;
    }
    public java.util.List<? extends com.google.protos.speech.common.Alternates.AlternateSpanOrBuilder> 
        getSpanOrBuilderList() {
      return span_;
    }
    public int getSpanCount() {
      return span_.size();
    }
    public com.google.protos.speech.common.Alternates.AlternateSpan getSpan(int index) {
      return span_.get(index);
    }
    public com.google.protos.speech.common.Alternates.AlternateSpanOrBuilder getSpanOrBuilder(
        int index) {
      return span_.get(index);
    }
    
    // required int32 maxSpanLength = 2;
    public static final int MAXSPANLENGTH_FIELD_NUMBER = 2;
    private int maxSpanLength_;
    public boolean hasMaxSpanLength() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMaxSpanLength() {
      return maxSpanLength_;
    }
    
    private void initFields() {
      span_ = java.util.Collections.emptyList();
      maxSpanLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMaxSpanLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSpanCount(); i++) {
        if (!getSpan(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < span_.size(); i++) {
        output.writeMessage(1, span_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, maxSpanLength_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < span_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, span_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxSpanLength_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.Alternates.RecognitionClientAlternates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.common.Alternates.RecognitionClientAlternates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.common.Alternates.RecognitionClientAlternates, Builder>
        implements com.google.protos.speech.common.Alternates.RecognitionClientAlternatesOrBuilder {
      // Construct using com.google.protos.speech.common.Alternates.RecognitionClientAlternates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        span_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSpanLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.common.Alternates.RecognitionClientAlternates getDefaultInstanceForType() {
        return com.google.protos.speech.common.Alternates.RecognitionClientAlternates.getDefaultInstance();
      }
      
      public com.google.protos.speech.common.Alternates.RecognitionClientAlternates build() {
        com.google.protos.speech.common.Alternates.RecognitionClientAlternates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.common.Alternates.RecognitionClientAlternates buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.common.Alternates.RecognitionClientAlternates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.common.Alternates.RecognitionClientAlternates buildPartial() {
        com.google.protos.speech.common.Alternates.RecognitionClientAlternates result = new com.google.protos.speech.common.Alternates.RecognitionClientAlternates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          span_ = java.util.Collections.unmodifiableList(span_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.span_ = span_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxSpanLength_ = maxSpanLength_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.common.Alternates.RecognitionClientAlternates other) {
        if (other == com.google.protos.speech.common.Alternates.RecognitionClientAlternates.getDefaultInstance()) return this;
        if (!other.span_.isEmpty()) {
          if (span_.isEmpty()) {
            span_ = other.span_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpanIsMutable();
            span_.addAll(other.span_);
          }
          
        }
        if (other.hasMaxSpanLength()) {
          setMaxSpanLength(other.getMaxSpanLength());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMaxSpanLength()) {
          
          return false;
        }
        for (int i = 0; i < getSpanCount(); i++) {
          if (!getSpan(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.speech.common.Alternates.AlternateSpan.Builder subBuilder = com.google.protos.speech.common.Alternates.AlternateSpan.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSpan(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxSpanLength_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .AlternateSpan span = 1;
      private java.util.List<com.google.protos.speech.common.Alternates.AlternateSpan> span_ =
        java.util.Collections.emptyList();
      private void ensureSpanIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          span_ = new java.util.ArrayList<com.google.protos.speech.common.Alternates.AlternateSpan>(span_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<com.google.protos.speech.common.Alternates.AlternateSpan> getSpanList() {
        return java.util.Collections.unmodifiableList(span_);
      }
      public int getSpanCount() {
        return span_.size();
      }
      public com.google.protos.speech.common.Alternates.AlternateSpan getSpan(int index) {
        return span_.get(index);
      }
      public Builder setSpan(
          int index, com.google.protos.speech.common.Alternates.AlternateSpan value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpanIsMutable();
        span_.set(index, value);
        
        return this;
      }
      public Builder setSpan(
          int index, com.google.protos.speech.common.Alternates.AlternateSpan.Builder builderForValue) {
        ensureSpanIsMutable();
        span_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addSpan(com.google.protos.speech.common.Alternates.AlternateSpan value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpanIsMutable();
        span_.add(value);
        
        return this;
      }
      public Builder addSpan(
          int index, com.google.protos.speech.common.Alternates.AlternateSpan value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpanIsMutable();
        span_.add(index, value);
        
        return this;
      }
      public Builder addSpan(
          com.google.protos.speech.common.Alternates.AlternateSpan.Builder builderForValue) {
        ensureSpanIsMutable();
        span_.add(builderForValue.build());
        
        return this;
      }
      public Builder addSpan(
          int index, com.google.protos.speech.common.Alternates.AlternateSpan.Builder builderForValue) {
        ensureSpanIsMutable();
        span_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllSpan(
          java.lang.Iterable<? extends com.google.protos.speech.common.Alternates.AlternateSpan> values) {
        ensureSpanIsMutable();
        super.addAll(values, span_);
        
        return this;
      }
      public Builder clearSpan() {
        span_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeSpan(int index) {
        ensureSpanIsMutable();
        span_.remove(index);
        
        return this;
      }
      
      // required int32 maxSpanLength = 2;
      private int maxSpanLength_ ;
      public boolean hasMaxSpanLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMaxSpanLength() {
        return maxSpanLength_;
      }
      public Builder setMaxSpanLength(int value) {
        bitField0_ |= 0x00000002;
        maxSpanLength_ = value;
        
        return this;
      }
      public Builder clearMaxSpanLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxSpanLength_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RecognitionClientAlternates)
    }
    
    static {
      defaultInstance = new RecognitionClientAlternates(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RecognitionClientAlternates)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
