// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/RecognitionContextProto.proto

package com.google.protos.speech.common;

public final class RecognitionContextProto {
  private RecognitionContextProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RecognitionContextOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string applicationName = 1;
    boolean hasApplicationName();
    String getApplicationName();
    
    // optional string fieldName = 2;
    boolean hasFieldName();
    String getFieldName();
    
    // optional string fieldId = 3;
    boolean hasFieldId();
    String getFieldId();
    
    // optional bool singleLine = 4;
    boolean hasSingleLine();
    boolean getSingleLine();
    
    // optional string label = 5;
    boolean hasLabel();
    String getLabel();
    
    // optional string hint = 6;
    boolean hasHint();
    String getHint();
    
    // optional int32 inputType = 7;
    boolean hasInputType();
    int getInputType();
    
    // optional int32 imeOptions = 8;
    boolean hasImeOptions();
    int getImeOptions();
    
    // optional string languageModel = 9;
    boolean hasLanguageModel();
    String getLanguageModel();
    
    // optional string language = 10;
    boolean hasLanguage();
    String getLanguage();
    
    // optional string clientId = 11;
    boolean hasClientId();
    String getClientId();
    
    // optional bool hasGrxmlGrammar = 12;
    boolean hasHasGrxmlGrammar();
    boolean getHasGrxmlGrammar();
    
    // optional string selectedKeyboardLanguage = 13;
    boolean hasSelectedKeyboardLanguage();
    String getSelectedKeyboardLanguage();
    
    // repeated string enabledKeyboardLanguage = 14;
    java.util.List<String> getEnabledKeyboardLanguageList();
    int getEnabledKeyboardLanguageCount();
    String getEnabledKeyboardLanguage(int index);
    
    // optional string voiceSearchLanguage = 15;
    boolean hasVoiceSearchLanguage();
    String getVoiceSearchLanguage();
    
    // optional string referer = 16;
    boolean hasReferer();
    String getReferer();
    
    // optional string userAgent = 17;
    boolean hasUserAgent();
    String getUserAgent();
    
    // optional string hardware = 18;
    boolean hasHardware();
    String getHardware();
    
    // optional string clientApplicationId = 19;
    boolean hasClientApplicationId();
    String getClientApplicationId();
  }
  public static final class RecognitionContext extends
      com.google.protobuf.GeneratedMessageLite
      implements RecognitionContextOrBuilder {
    // Use RecognitionContext.newBuilder() to construct.
    private RecognitionContext(Builder builder) {
      super(builder);
    }
    private RecognitionContext(boolean noInit) {}
    
    private static final RecognitionContext defaultInstance;
    public static RecognitionContext getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecognitionContext getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string applicationName = 1;
    public static final int APPLICATIONNAME_FIELD_NUMBER = 1;
    private java.lang.Object applicationName_;
    public boolean hasApplicationName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getApplicationName() {
      java.lang.Object ref = applicationName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationNameBytes() {
      java.lang.Object ref = applicationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string fieldName = 2;
    public static final int FIELDNAME_FIELD_NUMBER = 2;
    private java.lang.Object fieldName_;
    public boolean hasFieldName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFieldName() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fieldName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFieldNameBytes() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fieldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string fieldId = 3;
    public static final int FIELDID_FIELD_NUMBER = 3;
    private java.lang.Object fieldId_;
    public boolean hasFieldId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getFieldId() {
      java.lang.Object ref = fieldId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fieldId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFieldIdBytes() {
      java.lang.Object ref = fieldId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fieldId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool singleLine = 4;
    public static final int SINGLELINE_FIELD_NUMBER = 4;
    private boolean singleLine_;
    public boolean hasSingleLine() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getSingleLine() {
      return singleLine_;
    }
    
    // optional string label = 5;
    public static final int LABEL_FIELD_NUMBER = 5;
    private java.lang.Object label_;
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          label_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string hint = 6;
    public static final int HINT_FIELD_NUMBER = 6;
    private java.lang.Object hint_;
    public boolean hasHint() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getHint() {
      java.lang.Object ref = hint_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hint_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHintBytes() {
      java.lang.Object ref = hint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 inputType = 7;
    public static final int INPUTTYPE_FIELD_NUMBER = 7;
    private int inputType_;
    public boolean hasInputType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getInputType() {
      return inputType_;
    }
    
    // optional int32 imeOptions = 8;
    public static final int IMEOPTIONS_FIELD_NUMBER = 8;
    private int imeOptions_;
    public boolean hasImeOptions() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getImeOptions() {
      return imeOptions_;
    }
    
    // optional string languageModel = 9;
    public static final int LANGUAGEMODEL_FIELD_NUMBER = 9;
    private java.lang.Object languageModel_;
    public boolean hasLanguageModel() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getLanguageModel() {
      java.lang.Object ref = languageModel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          languageModel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLanguageModelBytes() {
      java.lang.Object ref = languageModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        languageModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string language = 10;
    public static final int LANGUAGE_FIELD_NUMBER = 10;
    private java.lang.Object language_;
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          language_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string clientId = 11;
    public static final int CLIENTID_FIELD_NUMBER = 11;
    private java.lang.Object clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool hasGrxmlGrammar = 12;
    public static final int HASGRXMLGRAMMAR_FIELD_NUMBER = 12;
    private boolean hasGrxmlGrammar_;
    public boolean hasHasGrxmlGrammar() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public boolean getHasGrxmlGrammar() {
      return hasGrxmlGrammar_;
    }
    
    // optional string selectedKeyboardLanguage = 13;
    public static final int SELECTEDKEYBOARDLANGUAGE_FIELD_NUMBER = 13;
    private java.lang.Object selectedKeyboardLanguage_;
    public boolean hasSelectedKeyboardLanguage() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getSelectedKeyboardLanguage() {
      java.lang.Object ref = selectedKeyboardLanguage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          selectedKeyboardLanguage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSelectedKeyboardLanguageBytes() {
      java.lang.Object ref = selectedKeyboardLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        selectedKeyboardLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string enabledKeyboardLanguage = 14;
    public static final int ENABLEDKEYBOARDLANGUAGE_FIELD_NUMBER = 14;
    private com.google.protobuf.LazyStringList enabledKeyboardLanguage_;
    public java.util.List<String>
        getEnabledKeyboardLanguageList() {
      return enabledKeyboardLanguage_;
    }
    public int getEnabledKeyboardLanguageCount() {
      return enabledKeyboardLanguage_.size();
    }
    public String getEnabledKeyboardLanguage(int index) {
      return enabledKeyboardLanguage_.get(index);
    }
    
    // optional string voiceSearchLanguage = 15;
    public static final int VOICESEARCHLANGUAGE_FIELD_NUMBER = 15;
    private java.lang.Object voiceSearchLanguage_;
    public boolean hasVoiceSearchLanguage() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public String getVoiceSearchLanguage() {
      java.lang.Object ref = voiceSearchLanguage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          voiceSearchLanguage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVoiceSearchLanguageBytes() {
      java.lang.Object ref = voiceSearchLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        voiceSearchLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string referer = 16;
    public static final int REFERER_FIELD_NUMBER = 16;
    private java.lang.Object referer_;
    public boolean hasReferer() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          referer_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string userAgent = 17;
    public static final int USERAGENT_FIELD_NUMBER = 17;
    private java.lang.Object userAgent_;
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userAgent_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string hardware = 18;
    public static final int HARDWARE_FIELD_NUMBER = 18;
    private java.lang.Object hardware_;
    public boolean hasHardware() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public String getHardware() {
      java.lang.Object ref = hardware_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hardware_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHardwareBytes() {
      java.lang.Object ref = hardware_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hardware_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string clientApplicationId = 19;
    public static final int CLIENTAPPLICATIONID_FIELD_NUMBER = 19;
    private java.lang.Object clientApplicationId_;
    public boolean hasClientApplicationId() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public String getClientApplicationId() {
      java.lang.Object ref = clientApplicationId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientApplicationId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientApplicationIdBytes() {
      java.lang.Object ref = clientApplicationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientApplicationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      applicationName_ = "";
      fieldName_ = "";
      fieldId_ = "";
      singleLine_ = false;
      label_ = "";
      hint_ = "";
      inputType_ = 0;
      imeOptions_ = 0;
      languageModel_ = "";
      language_ = "";
      clientId_ = "";
      hasGrxmlGrammar_ = false;
      selectedKeyboardLanguage_ = "";
      enabledKeyboardLanguage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      voiceSearchLanguage_ = "";
      referer_ = "";
      userAgent_ = "";
      hardware_ = "";
      clientApplicationId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getApplicationNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFieldNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFieldIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, singleLine_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLabelBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getHintBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, inputType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, imeOptions_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getLanguageModelBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getLanguageBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(12, hasGrxmlGrammar_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getSelectedKeyboardLanguageBytes());
      }
      for (int i = 0; i < enabledKeyboardLanguage_.size(); i++) {
        output.writeBytes(14, enabledKeyboardLanguage_.getByteString(i));
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(15, getVoiceSearchLanguageBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(16, getRefererBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(17, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(18, getHardwareBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(19, getClientApplicationIdBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getApplicationNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFieldNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFieldIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, singleLine_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLabelBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getHintBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, inputType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, imeOptions_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLanguageModelBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getLanguageBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, hasGrxmlGrammar_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getSelectedKeyboardLanguageBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < enabledKeyboardLanguage_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(enabledKeyboardLanguage_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getEnabledKeyboardLanguageList().size();
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getVoiceSearchLanguageBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getRefererBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getHardwareBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getClientApplicationIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.speech.common.RecognitionContextProto.RecognitionContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.speech.common.RecognitionContextProto.RecognitionContext prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.speech.common.RecognitionContextProto.RecognitionContext, Builder>
        implements com.google.protos.speech.common.RecognitionContextProto.RecognitionContextOrBuilder {
      // Construct using com.google.protos.speech.common.RecognitionContextProto.RecognitionContext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        applicationName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        singleLine_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        hint_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        inputType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        imeOptions_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        languageModel_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        language_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        hasGrxmlGrammar_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        selectedKeyboardLanguage_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        enabledKeyboardLanguage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00002000);
        voiceSearchLanguage_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        referer_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        hardware_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        clientApplicationId_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protos.speech.common.RecognitionContextProto.RecognitionContext getDefaultInstanceForType() {
        return com.google.protos.speech.common.RecognitionContextProto.RecognitionContext.getDefaultInstance();
      }
      
      public com.google.protos.speech.common.RecognitionContextProto.RecognitionContext build() {
        com.google.protos.speech.common.RecognitionContextProto.RecognitionContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.protos.speech.common.RecognitionContextProto.RecognitionContext buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.protos.speech.common.RecognitionContextProto.RecognitionContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.protos.speech.common.RecognitionContextProto.RecognitionContext buildPartial() {
        com.google.protos.speech.common.RecognitionContextProto.RecognitionContext result = new com.google.protos.speech.common.RecognitionContextProto.RecognitionContext(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.applicationName_ = applicationName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fieldName_ = fieldName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fieldId_ = fieldId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.singleLine_ = singleLine_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.hint_ = hint_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.inputType_ = inputType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.imeOptions_ = imeOptions_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.languageModel_ = languageModel_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.language_ = language_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.hasGrxmlGrammar_ = hasGrxmlGrammar_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.selectedKeyboardLanguage_ = selectedKeyboardLanguage_;
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          enabledKeyboardLanguage_ = new com.google.protobuf.UnmodifiableLazyStringList(
              enabledKeyboardLanguage_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.enabledKeyboardLanguage_ = enabledKeyboardLanguage_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.voiceSearchLanguage_ = voiceSearchLanguage_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.referer_ = referer_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.hardware_ = hardware_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.clientApplicationId_ = clientApplicationId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.google.protos.speech.common.RecognitionContextProto.RecognitionContext other) {
        if (other == com.google.protos.speech.common.RecognitionContextProto.RecognitionContext.getDefaultInstance()) return this;
        if (other.hasApplicationName()) {
          setApplicationName(other.getApplicationName());
        }
        if (other.hasFieldName()) {
          setFieldName(other.getFieldName());
        }
        if (other.hasFieldId()) {
          setFieldId(other.getFieldId());
        }
        if (other.hasSingleLine()) {
          setSingleLine(other.getSingleLine());
        }
        if (other.hasLabel()) {
          setLabel(other.getLabel());
        }
        if (other.hasHint()) {
          setHint(other.getHint());
        }
        if (other.hasInputType()) {
          setInputType(other.getInputType());
        }
        if (other.hasImeOptions()) {
          setImeOptions(other.getImeOptions());
        }
        if (other.hasLanguageModel()) {
          setLanguageModel(other.getLanguageModel());
        }
        if (other.hasLanguage()) {
          setLanguage(other.getLanguage());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasHasGrxmlGrammar()) {
          setHasGrxmlGrammar(other.getHasGrxmlGrammar());
        }
        if (other.hasSelectedKeyboardLanguage()) {
          setSelectedKeyboardLanguage(other.getSelectedKeyboardLanguage());
        }
        if (!other.enabledKeyboardLanguage_.isEmpty()) {
          if (enabledKeyboardLanguage_.isEmpty()) {
            enabledKeyboardLanguage_ = other.enabledKeyboardLanguage_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureEnabledKeyboardLanguageIsMutable();
            enabledKeyboardLanguage_.addAll(other.enabledKeyboardLanguage_);
          }
          
        }
        if (other.hasVoiceSearchLanguage()) {
          setVoiceSearchLanguage(other.getVoiceSearchLanguage());
        }
        if (other.hasReferer()) {
          setReferer(other.getReferer());
        }
        if (other.hasUserAgent()) {
          setUserAgent(other.getUserAgent());
        }
        if (other.hasHardware()) {
          setHardware(other.getHardware());
        }
        if (other.hasClientApplicationId()) {
          setClientApplicationId(other.getClientApplicationId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              applicationName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fieldName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fieldId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              singleLine_ = input.readBool();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              label_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              hint_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              inputType_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              imeOptions_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              languageModel_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              language_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              clientId_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              hasGrxmlGrammar_ = input.readBool();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              selectedKeyboardLanguage_ = input.readBytes();
              break;
            }
            case 114: {
              ensureEnabledKeyboardLanguageIsMutable();
              enabledKeyboardLanguage_.add(input.readBytes());
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              voiceSearchLanguage_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              referer_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              userAgent_ = input.readBytes();
              break;
            }
            case 146: {
              bitField0_ |= 0x00020000;
              hardware_ = input.readBytes();
              break;
            }
            case 154: {
              bitField0_ |= 0x00040000;
              clientApplicationId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string applicationName = 1;
      private java.lang.Object applicationName_ = "";
      public boolean hasApplicationName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getApplicationName() {
        java.lang.Object ref = applicationName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        applicationName_ = value;
        
        return this;
      }
      public Builder clearApplicationName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationName_ = getDefaultInstance().getApplicationName();
        
        return this;
      }
      void setApplicationName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        applicationName_ = value;
        
      }
      
      // optional string fieldName = 2;
      private java.lang.Object fieldName_ = "";
      public boolean hasFieldName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFieldName() {
        java.lang.Object ref = fieldName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fieldName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFieldName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fieldName_ = value;
        
        return this;
      }
      public Builder clearFieldName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldName_ = getDefaultInstance().getFieldName();
        
        return this;
      }
      void setFieldName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        fieldName_ = value;
        
      }
      
      // optional string fieldId = 3;
      private java.lang.Object fieldId_ = "";
      public boolean hasFieldId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getFieldId() {
        java.lang.Object ref = fieldId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fieldId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFieldId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fieldId_ = value;
        
        return this;
      }
      public Builder clearFieldId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldId_ = getDefaultInstance().getFieldId();
        
        return this;
      }
      void setFieldId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        fieldId_ = value;
        
      }
      
      // optional bool singleLine = 4;
      private boolean singleLine_ ;
      public boolean hasSingleLine() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getSingleLine() {
        return singleLine_;
      }
      public Builder setSingleLine(boolean value) {
        bitField0_ |= 0x00000008;
        singleLine_ = value;
        
        return this;
      }
      public Builder clearSingleLine() {
        bitField0_ = (bitField0_ & ~0x00000008);
        singleLine_ = false;
        
        return this;
      }
      
      // optional string label = 5;
      private java.lang.Object label_ = "";
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        label_ = value;
        
        return this;
      }
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        label_ = getDefaultInstance().getLabel();
        
        return this;
      }
      void setLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        label_ = value;
        
      }
      
      // optional string hint = 6;
      private java.lang.Object hint_ = "";
      public boolean hasHint() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getHint() {
        java.lang.Object ref = hint_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hint_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHint(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        hint_ = value;
        
        return this;
      }
      public Builder clearHint() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hint_ = getDefaultInstance().getHint();
        
        return this;
      }
      void setHint(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        hint_ = value;
        
      }
      
      // optional int32 inputType = 7;
      private int inputType_ ;
      public boolean hasInputType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getInputType() {
        return inputType_;
      }
      public Builder setInputType(int value) {
        bitField0_ |= 0x00000040;
        inputType_ = value;
        
        return this;
      }
      public Builder clearInputType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        inputType_ = 0;
        
        return this;
      }
      
      // optional int32 imeOptions = 8;
      private int imeOptions_ ;
      public boolean hasImeOptions() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getImeOptions() {
        return imeOptions_;
      }
      public Builder setImeOptions(int value) {
        bitField0_ |= 0x00000080;
        imeOptions_ = value;
        
        return this;
      }
      public Builder clearImeOptions() {
        bitField0_ = (bitField0_ & ~0x00000080);
        imeOptions_ = 0;
        
        return this;
      }
      
      // optional string languageModel = 9;
      private java.lang.Object languageModel_ = "";
      public boolean hasLanguageModel() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getLanguageModel() {
        java.lang.Object ref = languageModel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          languageModel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLanguageModel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        languageModel_ = value;
        
        return this;
      }
      public Builder clearLanguageModel() {
        bitField0_ = (bitField0_ & ~0x00000100);
        languageModel_ = getDefaultInstance().getLanguageModel();
        
        return this;
      }
      void setLanguageModel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        languageModel_ = value;
        
      }
      
      // optional string language = 10;
      private java.lang.Object language_ = "";
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLanguage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        language_ = value;
        
        return this;
      }
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000200);
        language_ = getDefaultInstance().getLanguage();
        
        return this;
      }
      void setLanguage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        language_ = value;
        
      }
      
      // optional string clientId = 11;
      private java.lang.Object clientId_ = "";
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        clientId_ = value;
        
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        clientId_ = getDefaultInstance().getClientId();
        
        return this;
      }
      void setClientId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        clientId_ = value;
        
      }
      
      // optional bool hasGrxmlGrammar = 12;
      private boolean hasGrxmlGrammar_ ;
      public boolean hasHasGrxmlGrammar() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public boolean getHasGrxmlGrammar() {
        return hasGrxmlGrammar_;
      }
      public Builder setHasGrxmlGrammar(boolean value) {
        bitField0_ |= 0x00000800;
        hasGrxmlGrammar_ = value;
        
        return this;
      }
      public Builder clearHasGrxmlGrammar() {
        bitField0_ = (bitField0_ & ~0x00000800);
        hasGrxmlGrammar_ = false;
        
        return this;
      }
      
      // optional string selectedKeyboardLanguage = 13;
      private java.lang.Object selectedKeyboardLanguage_ = "";
      public boolean hasSelectedKeyboardLanguage() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getSelectedKeyboardLanguage() {
        java.lang.Object ref = selectedKeyboardLanguage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          selectedKeyboardLanguage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSelectedKeyboardLanguage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        selectedKeyboardLanguage_ = value;
        
        return this;
      }
      public Builder clearSelectedKeyboardLanguage() {
        bitField0_ = (bitField0_ & ~0x00001000);
        selectedKeyboardLanguage_ = getDefaultInstance().getSelectedKeyboardLanguage();
        
        return this;
      }
      void setSelectedKeyboardLanguage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        selectedKeyboardLanguage_ = value;
        
      }
      
      // repeated string enabledKeyboardLanguage = 14;
      private com.google.protobuf.LazyStringList enabledKeyboardLanguage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEnabledKeyboardLanguageIsMutable() {
        if (!((bitField0_ & 0x00002000) == 0x00002000)) {
          enabledKeyboardLanguage_ = new com.google.protobuf.LazyStringArrayList(enabledKeyboardLanguage_);
          bitField0_ |= 0x00002000;
         }
      }
      public java.util.List<String>
          getEnabledKeyboardLanguageList() {
        return java.util.Collections.unmodifiableList(enabledKeyboardLanguage_);
      }
      public int getEnabledKeyboardLanguageCount() {
        return enabledKeyboardLanguage_.size();
      }
      public String getEnabledKeyboardLanguage(int index) {
        return enabledKeyboardLanguage_.get(index);
      }
      public Builder setEnabledKeyboardLanguage(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEnabledKeyboardLanguageIsMutable();
        enabledKeyboardLanguage_.set(index, value);
        
        return this;
      }
      public Builder addEnabledKeyboardLanguage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEnabledKeyboardLanguageIsMutable();
        enabledKeyboardLanguage_.add(value);
        
        return this;
      }
      public Builder addAllEnabledKeyboardLanguage(
          java.lang.Iterable<String> values) {
        ensureEnabledKeyboardLanguageIsMutable();
        super.addAll(values, enabledKeyboardLanguage_);
        
        return this;
      }
      public Builder clearEnabledKeyboardLanguage() {
        enabledKeyboardLanguage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00002000);
        
        return this;
      }
      void addEnabledKeyboardLanguage(com.google.protobuf.ByteString value) {
        ensureEnabledKeyboardLanguageIsMutable();
        enabledKeyboardLanguage_.add(value);
        
      }
      
      // optional string voiceSearchLanguage = 15;
      private java.lang.Object voiceSearchLanguage_ = "";
      public boolean hasVoiceSearchLanguage() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getVoiceSearchLanguage() {
        java.lang.Object ref = voiceSearchLanguage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          voiceSearchLanguage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVoiceSearchLanguage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        voiceSearchLanguage_ = value;
        
        return this;
      }
      public Builder clearVoiceSearchLanguage() {
        bitField0_ = (bitField0_ & ~0x00004000);
        voiceSearchLanguage_ = getDefaultInstance().getVoiceSearchLanguage();
        
        return this;
      }
      void setVoiceSearchLanguage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        voiceSearchLanguage_ = value;
        
      }
      
      // optional string referer = 16;
      private java.lang.Object referer_ = "";
      public boolean hasReferer() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReferer(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        referer_ = value;
        
        return this;
      }
      public Builder clearReferer() {
        bitField0_ = (bitField0_ & ~0x00008000);
        referer_ = getDefaultInstance().getReferer();
        
        return this;
      }
      void setReferer(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00008000;
        referer_ = value;
        
      }
      
      // optional string userAgent = 17;
      private java.lang.Object userAgent_ = "";
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserAgent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        userAgent_ = value;
        
        return this;
      }
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00010000);
        userAgent_ = getDefaultInstance().getUserAgent();
        
        return this;
      }
      void setUserAgent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00010000;
        userAgent_ = value;
        
      }
      
      // optional string hardware = 18;
      private java.lang.Object hardware_ = "";
      public boolean hasHardware() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public String getHardware() {
        java.lang.Object ref = hardware_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hardware_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHardware(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        hardware_ = value;
        
        return this;
      }
      public Builder clearHardware() {
        bitField0_ = (bitField0_ & ~0x00020000);
        hardware_ = getDefaultInstance().getHardware();
        
        return this;
      }
      void setHardware(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00020000;
        hardware_ = value;
        
      }
      
      // optional string clientApplicationId = 19;
      private java.lang.Object clientApplicationId_ = "";
      public boolean hasClientApplicationId() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public String getClientApplicationId() {
        java.lang.Object ref = clientApplicationId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientApplicationId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientApplicationId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        clientApplicationId_ = value;
        
        return this;
      }
      public Builder clearClientApplicationId() {
        bitField0_ = (bitField0_ & ~0x00040000);
        clientApplicationId_ = getDefaultInstance().getClientApplicationId();
        
        return this;
      }
      void setClientApplicationId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00040000;
        clientApplicationId_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:RecognitionContext)
    }
    
    static {
      defaultInstance = new RecognitionContext(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RecognitionContext)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
